#!/bin/sh

PROJECT=$(cd "$(dirname "$0")/.." && pwd)
cd "$PROJECT" || exit 1

TEST_VMS_S3_ENDPOINT='https://5d79a0473b8621a40befe75f1eba08e8.r2.cloudflarestorage.com'
export TEST_VMS_S3_ENDPOINT
TEST_VMS_S3_BUCKET='socklink-test-vms'
export TEST_VMS_S3_BUCKET

PYTHON_MIN=3.11
PYTHON_BINS="python3.15 python3.14 python3.13 python3.12 python3.11 python3 python"

python_version_at_least() {
	result=$("$1" -c "import sys; print(float(f'{sys.version_info[0]}.{sys.version_info[1]}') >= $2)")
	if [ "$result" != "True" ]; then
		false
	fi
}

# Searches Python binary candidate names for the first one matching our
# minimum version requirement.
get_python_bin() {
	for bin in $PYTHON_BINS; do
		if which "$bin" >/dev/null 2>&1 \
				&& python_version_at_least "$bin" "$PYTHON_MIN"; then
			ver=$("$bin" --version)
			echo "Using bin $bin, version $ver" >&2
			echo "$bin"
			return
		fi
	done
	echo "No supported Python version found, aborting" >&2
	exit 1
}

setup_venv() {
	if [ ! -d "${PROJECT}/.venv" ]; then
		echo "Preparing venv"
		py="$(get_python_bin)"
		"$py" -m venv "${PROJECT}/.venv"
	fi
}

find_docker() {
	if podman -v >/dev/null 2>&1; then
		which podman
	elif docker -v >/dev/null 2>&1; then
		which docker
	else
		echo "No podman or docker binary found!" >&2
		exit 1
	fi
}

latest_mtime_recursive() {
	path="$1"
	find "$path" -print0 | xargs -0I{} date -r {} '+%s' | sort -nr | head -n 1
}

copy_ci_requirements() {
	dest="$1"

	if [ -z "$dest" ]; then
		echo "Missing dest argument" >&2
		exit 2
	fi

	items="\
conftest.py
dev-requirements.txt
pyproject.toml
pyrightconfig.json
requirements.txt
scripts
shellcheckrc
socklink.sh
tests
"

	if [ ! -d "$dest" ]; then
		mkdir -p "$dest"
	fi
	rm -rf "${dest:?}"/*

	for item in $items; do
		cp -pr "$PROJECT/$item" "$dest/$item"
	done
}

make_ci_iso() {
	iso_out="$PROJECT/vms/socklink.iso"
	mkdir -p "$(dirname "$iso_out")"

	iso_src="$(mktemp -d)"
	trap 'rm -rf -- "$iso_src"' EXIT

	copy_ci_requirements "$iso_src/"
	if [ -e "$iso_out" ]; then
		rm -f "$iso_out"
	fi
	xorriso -as mkisofs -o "$iso_out" "$iso_src"
}
