#!/bin/sh

PROJECT=$(cd "$(dirname "$0")/.." && pwd)
cd "$PROJECT" || exit 1

TEST_VMS_S3_ENDPOINT='https://5d79a0473b8621a40befe75f1eba08e8.r2.cloudflarestorage.com'
export TEST_VMS_S3_ENDPOINT
TEST_VMS_S3_BUCKET='socklink-test-vms'
export TEST_VMS_S3_BUCKET

find_docker() {
	if podman -v >/dev/null 2>&1; then
		which podman
	elif docker -v >/dev/null 2>&1; then
		which docker
	else
		echo "No podman or docker binary found!" >&2
		exit 1
	fi
}

latest_mtime_recursive() {
	path="$1"
	find "$path" -print0 | xargs -0I{} date -r {} '+%s' | sort -nr | head -n 1
}

copy_ci_requirements() {
	dest="$1"

	if [ -z "$dest" ]; then
		echo "Missing dest argument" >&2
		exit 2
	fi

	items="\
conftest.py
dev-requirements.txt
pyproject.toml
pyrightconfig.json
requirements.txt
scripts
socklink.sh
tests
"

	if [ ! -d "$dest" ]; then
		mkdir -p "$dest"
	fi
	rm -rf "${dest:?}"/*

	for item in $items; do
		cp -pr "$PROJECT/$item" "$dest/$item"
	done
}

make_ci_iso() {
	iso_out="$PROJECT/vms/socklink.iso"
	mkdir -p "$(dirname "$iso_out")"

	iso_src="$(mktemp -d)"
	trap 'rm -rf -- "$iso_src"' EXIT

	copy_ci_requirements "$iso_src/"
	if [ -e "$iso_out" ]; then
		rm -f "$iso_out"
	fi
	xorriso -as mkisofs -o "$iso_out" "$iso_src"
}
