name: Test
on:
  workflow_call:
    inputs:
      vm:
        required: true
        type: string
      host-os:
        required: false
        type: string
        default: ubuntu-26.04

jobs:
  test:
    runs-on: ${{ inputs.host-os }}
    steps:
      - uses: actions/checkout@v7

      - name: Install Ubuntu packages
        run: sudo apt update && sudo apt install -y qemu-system-x86 qemu-utils xorriso

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls -l /dev/kvm

      - name: Fetch vm
        env:
          SOCKLINK_TEST_VMS_ACCESS_KEY_ID: "${{ secrets.SOCKLINK_TEST_VMS_ACCESS_KEY_ID }}"
          SOCKLINK_TEST_VMS_SECRET_ACCESS_KEY: "${{ secrets.SOCKLINK_TEST_VMS_SECRET_ACCESS_KEY }}"
        run: scripts/fetch_vm.sh "${{ inputs.vm }}"

      - name: Run tests in vm
        run: scripts/test.sh -m "${{ inputs.vm }}"
