name: Test
on:
  workflow_call:
    inputs:
      container:
        required: true
        type: string
      host-os:
        required: false
        type: string
        default: ubuntu-26.04-arm

jobs:
  test:
    runs-on: ${{ inputs.host-os }}
    steps:
      - uses: actions/checkout@v7

      - name: Run tests in container
        run: scripts/test.sh -c ${{ inputs.container }}
