name: ci
on:
  workflow_call:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  lint_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    uses: ./.github/workflows/lint-and-test.yml
    with:
      os: ${{ matrix.os }}
