name: Lint
on:
  workflow_call:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: sudo apt install -y emacs-nox shellcheck

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Get the same version of ruff as in our development environment.
      - name: Setup venv
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r dev-requirements.txt

      - name: Lint
        run: scripts/lint.sh
