name: Periodic
on:
  workflow_dispatch:
  schedule:
    - cron: "57 0 * * 3"

jobs:
  lint_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-latest
          - macos-15
          - macos-14
          - macos-13
    uses: ./.github/workflows/lint-and-test.yml
    with:
      os: ${{ matrix.os }}
