name: Periodic
on:
  workflow_dispatch:
  schedule:
    - cron: "57 0 * * 3"

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04
          - macos-latest
          - macos-13
    uses: ./.github/workflows/test.yml
    with:
      os: ${{ matrix.os }}

  sourcehut:
    uses: ./.github/workflows/sourcehut.yml
