name: SourceHut
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "57 0 * * 1,4"

jobs:
  sourcehut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup venv
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r dev-requirements.txt

      - name: Run tests on SourceHut Builds
        env:
          SOURCEHUT_ACCESS_TOKEN: ${{ secrets.SOURCEHUT_ACCESS_TOKEN }}
          GH_TOKEN: ${{ github.token }}
        run: |
          run_url=$(gh run --repo ${{ github.repository }} view ${{ github.run_id }} --json jobs --jq '.jobs[] | select(.name == "${{ github.job }}") | .url')
          . .venv/bin/activate
          python scripts/srht.py scripts/srht_manifests \
              --repo https://github.com/${{ github.repository }} --commit ${{ github.sha }} \
              --trigger "$run_url"
