name: Test Ubuntu
on:
  workflow_call:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
  schedule:
    - cron: "57 0 * * 1,4"

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      os: ubuntu-latest
