name: CI
on:
  workflow_call:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  lint_and_test:
    uses: ./.github/workflows/lint-and-test.yml
    with:
      os: ubuntu-latest
