name: test-freebsd
on:
  workflow_call:
  workflow_dispatch:
  # schedule:
  #   - cron: "57 15 * * 1"

jobs:
  test:
    uses: ./.github/workflows/action-test-vm.yml
    secrets: inherit
    with:
      vm: freebsd15
