name: Test
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: Homebrew/actions/setup-homebrew@main
        if: ${{ contains(inputs.os, 'macos-') }}

      - name: Install tmux
        run: brew install tmux
        if: ${{ contains(inputs.os, 'macos-') }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run tests
        # Run the tests in ./pytest to avoid "File name too long" in the
        # default location on macOS
        run: scripts/test.sh --basetemp ./pytest
